vars {
  entry {
    key: "repl"
    wrapper_typename: "EnvFunctorEntry"
    [ok_msg.EnvFunctorEntryDataSVMapEntry_field] {
      func {
        alias: "fsl::Stream"
        [ok_msg.StreamInit.stream] {
          src: { alias: "fsl::stdin" }
		  proc: { alias: "fsl::oarph" }
          snk: { alias: "fsl::stdout" }
        }
      }
    }
  }
  entry {
    key: "env.main"
    wrapper_typename: "EnvMainAttr"
    dyndata {
      vStr: "repl"
    }
  }
}
