// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: TestMessage.capnp

#include "TestMessage.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<64> b_b98d52b750cec8ee = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    238, 200, 206,  80, 183,  82, 141, 185,
     18,   0,   0,   0,   1,   0,   0,   0,
    228, 190,  38,  16, 237,  12, 112, 233,
      3,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 242,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 175,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     84, 101, 115, 116,  77, 101, 115, 115,
     97, 103, 101,  46,  99,  97, 112, 110,
    112,  58,  84, 101, 115, 116,  77, 101,
    115, 115,  97, 103, 101,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     12,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     68,   0,   0,   0,   2,   0,   1,   0,
     76,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     73,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     68,   0,   0,   0,   2,   0,   1,   0,
     76,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     73,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     68,   0,   0,   0,   2,   0,   1,   0,
     88,   0,   0,   0,   2,   0,   1,   0,
    114,  97, 119,  66, 121, 116, 101, 115,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114,  97, 119,  83, 116, 114,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    110, 117, 109, 115,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   2,   0,   1,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_b98d52b750cec8ee = b_b98d52b750cec8ee.words;
#if !CAPNP_LITE
static const uint16_t m_b98d52b750cec8ee[] = {2, 0, 1};
static const uint16_t i_b98d52b750cec8ee[] = {0, 1, 2};
const ::capnp::_::RawSchema s_b98d52b750cec8ee = {
  0xb98d52b750cec8ee, b_b98d52b750cec8ee.words, 64, nullptr, m_b98d52b750cec8ee,
  0, 3, i_b98d52b750cec8ee, nullptr, nullptr, { &s_b98d52b750cec8ee, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================

namespace ok_test_msg {
namespace capnpm {

// TestMessage
#ifndef _MSC_VER
constexpr uint16_t TestMessage::_capnpPrivate::dataWordSize;
constexpr uint16_t TestMessage::_capnpPrivate::pointerCount;
#endif
#if !CAPNP_LITE
constexpr ::capnp::Kind TestMessage::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* TestMessage::_capnpPrivate::schema;
constexpr ::capnp::_::RawBrandedSchema const* TestMessage::_capnpPrivate::brand;
#endif  // !CAPNP_LITE


}  // namespace
}  // namespace

