// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ok_msg/FLiSpec.proto

#ifndef PROTOBUF_ok_5fmsg_2fFLiSpec_2eproto__INCLUDED
#define PROTOBUF_ok_5fmsg_2fFLiSpec_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ok_msg/DynamicProto.pb.h"
#include "ok_msg/SVMapData.pb.h"
// @@protoc_insertion_point(includes)

namespace ok_msg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

class EnvFunctorEntryData;
class Func;
class EnvState;
class CompositionInit;
class WhileInit;
class StreamInit;
class TopKSinkInit;
class RangeInit;

// ===================================================================

class EnvFunctorEntryData : public ::google::protobuf::Message {
 public:
  EnvFunctorEntryData();
  virtual ~EnvFunctorEntryData();

  EnvFunctorEntryData(const EnvFunctorEntryData& from);

  inline EnvFunctorEntryData& operator=(const EnvFunctorEntryData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnvFunctorEntryData& default_instance();

  void Swap(EnvFunctorEntryData* other);

  // implements Message ----------------------------------------------

  EnvFunctorEntryData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnvFunctorEntryData& from);
  void MergeFrom(const EnvFunctorEntryData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ok_msg.Func func = 1;
  inline bool has_func() const;
  inline void clear_func();
  static const int kFuncFieldNumber = 1;
  inline const ::ok_msg::Func& func() const;
  inline ::ok_msg::Func* mutable_func();
  inline ::ok_msg::Func* release_func();
  inline void set_allocated_func(::ok_msg::Func* func);

  // optional .ok_msg.SVMapData attrs = 2;
  inline bool has_attrs() const;
  inline void clear_attrs();
  static const int kAttrsFieldNumber = 2;
  inline const ::ok_msg::SVMapData& attrs() const;
  inline ::ok_msg::SVMapData* mutable_attrs();
  inline ::ok_msg::SVMapData* release_attrs();
  inline void set_allocated_attrs(::ok_msg::SVMapData* attrs);

  // @@protoc_insertion_point(class_scope:ok_msg.EnvFunctorEntryData)
 private:
  inline void set_has_func();
  inline void clear_has_func();
  inline void set_has_attrs();
  inline void clear_has_attrs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ok_msg::Func* func_;
  ::ok_msg::SVMapData* attrs_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static EnvFunctorEntryData* default_instance_;
};
// -------------------------------------------------------------------

class Func : public ::google::protobuf::Message {
 public:
  Func();
  virtual ~Func();

  Func(const Func& from);

  inline Func& operator=(const Func& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Func& default_instance();

  void Swap(Func* other);

  // implements Message ----------------------------------------------

  Func* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Func& from);
  void MergeFrom(const Func& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string alias = 1;
  inline bool has_alias() const;
  inline void clear_alias();
  static const int kAliasFieldNumber = 1;
  inline const ::std::string& alias() const;
  inline void set_alias(const ::std::string& value);
  inline void set_alias(const char* value);
  inline void set_alias(const char* value, size_t size);
  inline ::std::string* mutable_alias();
  inline ::std::string* release_alias();
  inline void set_allocated_alias(::std::string* alias);

  // optional string name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional .ok_msg.DynamicProto fli_dyn_params = 2;
  inline bool has_fli_dyn_params() const;
  inline void clear_fli_dyn_params();
  static const int kFliDynParamsFieldNumber = 2;
  inline const ::ok_msg::DynamicProto& fli_dyn_params() const;
  inline ::ok_msg::DynamicProto* mutable_fli_dyn_params();
  inline ::ok_msg::DynamicProto* release_fli_dyn_params();
  inline void set_allocated_fli_dyn_params(::ok_msg::DynamicProto* fli_dyn_params);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(Func)
  // @@protoc_insertion_point(class_scope:ok_msg.Func)
 private:
  inline void set_has_alias();
  inline void clear_has_alias();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_fli_dyn_params();
  inline void clear_has_fli_dyn_params();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* alias_;
  ::std::string* name_;
  ::ok_msg::DynamicProto* fli_dyn_params_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static Func* default_instance_;
};
// -------------------------------------------------------------------

class EnvState : public ::google::protobuf::Message {
 public:
  EnvState();
  virtual ~EnvState();

  EnvState(const EnvState& from);

  inline EnvState& operator=(const EnvState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnvState& default_instance();

  void Swap(EnvState* other);

  // implements Message ----------------------------------------------

  EnvState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnvState& from);
  void MergeFrom(const EnvState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .ok_msg.SVMapData vars = 1;
  inline bool has_vars() const;
  inline void clear_vars();
  static const int kVarsFieldNumber = 1;
  inline const ::ok_msg::SVMapData& vars() const;
  inline ::ok_msg::SVMapData* mutable_vars();
  inline ::ok_msg::SVMapData* release_vars();
  inline void set_allocated_vars(::ok_msg::SVMapData* vars);

  // @@protoc_insertion_point(class_scope:ok_msg.EnvState)
 private:
  inline void set_has_vars();
  inline void clear_has_vars();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ok_msg::SVMapData* vars_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static EnvState* default_instance_;
};
// -------------------------------------------------------------------

class CompositionInit : public ::google::protobuf::Message {
 public:
  CompositionInit();
  virtual ~CompositionInit();

  CompositionInit(const CompositionInit& from);

  inline CompositionInit& operator=(const CompositionInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CompositionInit& default_instance();

  void Swap(CompositionInit* other);

  // implements Message ----------------------------------------------

  CompositionInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CompositionInit& from);
  void MergeFrom(const CompositionInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ok_msg.Func func = 1;
  inline int func_size() const;
  inline void clear_func();
  static const int kFuncFieldNumber = 1;
  inline const ::ok_msg::Func& func(int index) const;
  inline ::ok_msg::Func* mutable_func(int index);
  inline ::ok_msg::Func* add_func();
  inline const ::google::protobuf::RepeatedPtrField< ::ok_msg::Func >&
      func() const;
  inline ::google::protobuf::RepeatedPtrField< ::ok_msg::Func >*
      mutable_func();

  static const int kCompositionFieldNumber = 100;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ok_msg::Func,
      ::google::protobuf::internal::MessageTypeTraits< ::ok_msg::CompositionInit >, 11, false >
    composition;
  // @@protoc_insertion_point(class_scope:ok_msg.CompositionInit)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ok_msg::Func > func_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static CompositionInit* default_instance_;
};
// -------------------------------------------------------------------

class WhileInit : public ::google::protobuf::Message {
 public:
  WhileInit();
  virtual ~WhileInit();

  WhileInit(const WhileInit& from);

  inline WhileInit& operator=(const WhileInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WhileInit& default_instance();

  void Swap(WhileInit* other);

  // implements Message ----------------------------------------------

  WhileInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WhileInit& from);
  void MergeFrom(const WhileInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ok_msg.Func condition = 1;
  inline bool has_condition() const;
  inline void clear_condition();
  static const int kConditionFieldNumber = 1;
  inline const ::ok_msg::Func& condition() const;
  inline ::ok_msg::Func* mutable_condition();
  inline ::ok_msg::Func* release_condition();
  inline void set_allocated_condition(::ok_msg::Func* condition);

  // optional .ok_msg.Func body = 2;
  inline bool has_body() const;
  inline void clear_body();
  static const int kBodyFieldNumber = 2;
  inline const ::ok_msg::Func& body() const;
  inline ::ok_msg::Func* mutable_body();
  inline ::ok_msg::Func* release_body();
  inline void set_allocated_body(::ok_msg::Func* body);

  static const int kWhileFieldNumber = 101;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ok_msg::Func,
      ::google::protobuf::internal::MessageTypeTraits< ::ok_msg::WhileInit >, 11, false >
    while_;
  // @@protoc_insertion_point(class_scope:ok_msg.WhileInit)
 private:
  inline void set_has_condition();
  inline void clear_has_condition();
  inline void set_has_body();
  inline void clear_has_body();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ok_msg::Func* condition_;
  ::ok_msg::Func* body_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static WhileInit* default_instance_;
};
// -------------------------------------------------------------------

class StreamInit : public ::google::protobuf::Message {
 public:
  StreamInit();
  virtual ~StreamInit();

  StreamInit(const StreamInit& from);

  inline StreamInit& operator=(const StreamInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StreamInit& default_instance();

  void Swap(StreamInit* other);

  // implements Message ----------------------------------------------

  StreamInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StreamInit& from);
  void MergeFrom(const StreamInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ok_msg.Func src = 1;
  inline bool has_src() const;
  inline void clear_src();
  static const int kSrcFieldNumber = 1;
  inline const ::ok_msg::Func& src() const;
  inline ::ok_msg::Func* mutable_src();
  inline ::ok_msg::Func* release_src();
  inline void set_allocated_src(::ok_msg::Func* src);

  // optional .ok_msg.Func snk = 2;
  inline bool has_snk() const;
  inline void clear_snk();
  static const int kSnkFieldNumber = 2;
  inline const ::ok_msg::Func& snk() const;
  inline ::ok_msg::Func* mutable_snk();
  inline ::ok_msg::Func* release_snk();
  inline void set_allocated_snk(::ok_msg::Func* snk);

  static const int kStreamFieldNumber = 102;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ok_msg::Func,
      ::google::protobuf::internal::MessageTypeTraits< ::ok_msg::StreamInit >, 11, false >
    stream;
  // @@protoc_insertion_point(class_scope:ok_msg.StreamInit)
 private:
  inline void set_has_src();
  inline void clear_has_src();
  inline void set_has_snk();
  inline void clear_has_snk();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ok_msg::Func* src_;
  ::ok_msg::Func* snk_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static StreamInit* default_instance_;
};
// -------------------------------------------------------------------

class TopKSinkInit : public ::google::protobuf::Message {
 public:
  TopKSinkInit();
  virtual ~TopKSinkInit();

  TopKSinkInit(const TopKSinkInit& from);

  inline TopKSinkInit& operator=(const TopKSinkInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TopKSinkInit& default_instance();

  void Swap(TopKSinkInit* other);

  // implements Message ----------------------------------------------

  TopKSinkInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TopKSinkInit& from);
  void MergeFrom(const TopKSinkInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 k = 1;
  inline bool has_k() const;
  inline void clear_k();
  static const int kKFieldNumber = 1;
  inline ::google::protobuf::uint64 k() const;
  inline void set_k(::google::protobuf::uint64 value);

  static const int kTopkSinkFieldNumber = 103;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ok_msg::Func,
      ::google::protobuf::internal::MessageTypeTraits< ::ok_msg::TopKSinkInit >, 11, false >
    topk_sink;
  // @@protoc_insertion_point(class_scope:ok_msg.TopKSinkInit)
 private:
  inline void set_has_k();
  inline void clear_has_k();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 k_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static TopKSinkInit* default_instance_;
};
// -------------------------------------------------------------------

class RangeInit : public ::google::protobuf::Message {
 public:
  RangeInit();
  virtual ~RangeInit();

  RangeInit(const RangeInit& from);

  inline RangeInit& operator=(const RangeInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RangeInit& default_instance();

  void Swap(RangeInit* other);

  // implements Message ----------------------------------------------

  RangeInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RangeInit& from);
  void MergeFrom(const RangeInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 start = 1;
  inline bool has_start() const;
  inline void clear_start();
  static const int kStartFieldNumber = 1;
  inline ::google::protobuf::int64 start() const;
  inline void set_start(::google::protobuf::int64 value);

  // optional int64 step = 2;
  inline bool has_step() const;
  inline void clear_step();
  static const int kStepFieldNumber = 2;
  inline ::google::protobuf::int64 step() const;
  inline void set_step(::google::protobuf::int64 value);

  // required int64 limit = 3;
  inline bool has_limit() const;
  inline void clear_limit();
  static const int kLimitFieldNumber = 3;
  inline ::google::protobuf::int64 limit() const;
  inline void set_limit(::google::protobuf::int64 value);

  static const int kRangeFieldNumber = 104;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ok_msg::Func,
      ::google::protobuf::internal::MessageTypeTraits< ::ok_msg::RangeInit >, 11, false >
    range;
  // @@protoc_insertion_point(class_scope:ok_msg.RangeInit)
 private:
  inline void set_has_start();
  inline void clear_has_start();
  inline void set_has_step();
  inline void clear_has_step();
  inline void set_has_limit();
  inline void clear_has_limit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 start_;
  ::google::protobuf::int64 step_;
  ::google::protobuf::int64 limit_;
  friend void  protobuf_AddDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_AssignDesc_ok_5fmsg_2fFLiSpec_2eproto();
  friend void protobuf_ShutdownFile_ok_5fmsg_2fFLiSpec_2eproto();

  void InitAsDefaultInstance();
  static RangeInit* default_instance_;
};
// ===================================================================

static const int kEnvFunctorEntryDataSVMapEntryFieldFieldNumber = 150;
extern ::google::protobuf::internal::ExtensionIdentifier< ::ok_msg::SVMapEntryData,
    ::google::protobuf::internal::MessageTypeTraits< ::ok_msg::EnvFunctorEntryData >, 11, false >
  EnvFunctorEntryDataSVMapEntry_field;

// ===================================================================

// EnvFunctorEntryData

// optional .ok_msg.Func func = 1;
inline bool EnvFunctorEntryData::has_func() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EnvFunctorEntryData::set_has_func() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EnvFunctorEntryData::clear_has_func() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EnvFunctorEntryData::clear_func() {
  if (func_ != NULL) func_->::ok_msg::Func::Clear();
  clear_has_func();
}
inline const ::ok_msg::Func& EnvFunctorEntryData::func() const {
  // @@protoc_insertion_point(field_get:ok_msg.EnvFunctorEntryData.func)
  return func_ != NULL ? *func_ : *default_instance_->func_;
}
inline ::ok_msg::Func* EnvFunctorEntryData::mutable_func() {
  set_has_func();
  if (func_ == NULL) func_ = new ::ok_msg::Func;
  // @@protoc_insertion_point(field_mutable:ok_msg.EnvFunctorEntryData.func)
  return func_;
}
inline ::ok_msg::Func* EnvFunctorEntryData::release_func() {
  clear_has_func();
  ::ok_msg::Func* temp = func_;
  func_ = NULL;
  return temp;
}
inline void EnvFunctorEntryData::set_allocated_func(::ok_msg::Func* func) {
  delete func_;
  func_ = func;
  if (func) {
    set_has_func();
  } else {
    clear_has_func();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.EnvFunctorEntryData.func)
}

// optional .ok_msg.SVMapData attrs = 2;
inline bool EnvFunctorEntryData::has_attrs() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EnvFunctorEntryData::set_has_attrs() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EnvFunctorEntryData::clear_has_attrs() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EnvFunctorEntryData::clear_attrs() {
  if (attrs_ != NULL) attrs_->::ok_msg::SVMapData::Clear();
  clear_has_attrs();
}
inline const ::ok_msg::SVMapData& EnvFunctorEntryData::attrs() const {
  // @@protoc_insertion_point(field_get:ok_msg.EnvFunctorEntryData.attrs)
  return attrs_ != NULL ? *attrs_ : *default_instance_->attrs_;
}
inline ::ok_msg::SVMapData* EnvFunctorEntryData::mutable_attrs() {
  set_has_attrs();
  if (attrs_ == NULL) attrs_ = new ::ok_msg::SVMapData;
  // @@protoc_insertion_point(field_mutable:ok_msg.EnvFunctorEntryData.attrs)
  return attrs_;
}
inline ::ok_msg::SVMapData* EnvFunctorEntryData::release_attrs() {
  clear_has_attrs();
  ::ok_msg::SVMapData* temp = attrs_;
  attrs_ = NULL;
  return temp;
}
inline void EnvFunctorEntryData::set_allocated_attrs(::ok_msg::SVMapData* attrs) {
  delete attrs_;
  attrs_ = attrs;
  if (attrs) {
    set_has_attrs();
  } else {
    clear_has_attrs();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.EnvFunctorEntryData.attrs)
}

// -------------------------------------------------------------------

// Func

// optional string alias = 1;
inline bool Func::has_alias() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Func::set_has_alias() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Func::clear_has_alias() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Func::clear_alias() {
  if (alias_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alias_->clear();
  }
  clear_has_alias();
}
inline const ::std::string& Func::alias() const {
  // @@protoc_insertion_point(field_get:ok_msg.Func.alias)
  return *alias_;
}
inline void Func::set_alias(const ::std::string& value) {
  set_has_alias();
  if (alias_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alias_ = new ::std::string;
  }
  alias_->assign(value);
  // @@protoc_insertion_point(field_set:ok_msg.Func.alias)
}
inline void Func::set_alias(const char* value) {
  set_has_alias();
  if (alias_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alias_ = new ::std::string;
  }
  alias_->assign(value);
  // @@protoc_insertion_point(field_set_char:ok_msg.Func.alias)
}
inline void Func::set_alias(const char* value, size_t size) {
  set_has_alias();
  if (alias_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alias_ = new ::std::string;
  }
  alias_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ok_msg.Func.alias)
}
inline ::std::string* Func::mutable_alias() {
  set_has_alias();
  if (alias_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alias_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ok_msg.Func.alias)
  return alias_;
}
inline ::std::string* Func::release_alias() {
  clear_has_alias();
  if (alias_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = alias_;
    alias_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Func::set_allocated_alias(::std::string* alias) {
  if (alias_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete alias_;
  }
  if (alias) {
    set_has_alias();
    alias_ = alias;
  } else {
    clear_has_alias();
    alias_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.Func.alias)
}

// optional string name = 3;
inline bool Func::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Func::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Func::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Func::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Func::name() const {
  // @@protoc_insertion_point(field_get:ok_msg.Func.name)
  return *name_;
}
inline void Func::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:ok_msg.Func.name)
}
inline void Func::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:ok_msg.Func.name)
}
inline void Func::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ok_msg.Func.name)
}
inline ::std::string* Func::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ok_msg.Func.name)
  return name_;
}
inline ::std::string* Func::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Func::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.Func.name)
}

// optional .ok_msg.DynamicProto fli_dyn_params = 2;
inline bool Func::has_fli_dyn_params() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Func::set_has_fli_dyn_params() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Func::clear_has_fli_dyn_params() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Func::clear_fli_dyn_params() {
  if (fli_dyn_params_ != NULL) fli_dyn_params_->::ok_msg::DynamicProto::Clear();
  clear_has_fli_dyn_params();
}
inline const ::ok_msg::DynamicProto& Func::fli_dyn_params() const {
  // @@protoc_insertion_point(field_get:ok_msg.Func.fli_dyn_params)
  return fli_dyn_params_ != NULL ? *fli_dyn_params_ : *default_instance_->fli_dyn_params_;
}
inline ::ok_msg::DynamicProto* Func::mutable_fli_dyn_params() {
  set_has_fli_dyn_params();
  if (fli_dyn_params_ == NULL) fli_dyn_params_ = new ::ok_msg::DynamicProto;
  // @@protoc_insertion_point(field_mutable:ok_msg.Func.fli_dyn_params)
  return fli_dyn_params_;
}
inline ::ok_msg::DynamicProto* Func::release_fli_dyn_params() {
  clear_has_fli_dyn_params();
  ::ok_msg::DynamicProto* temp = fli_dyn_params_;
  fli_dyn_params_ = NULL;
  return temp;
}
inline void Func::set_allocated_fli_dyn_params(::ok_msg::DynamicProto* fli_dyn_params) {
  delete fli_dyn_params_;
  fli_dyn_params_ = fli_dyn_params;
  if (fli_dyn_params) {
    set_has_fli_dyn_params();
  } else {
    clear_has_fli_dyn_params();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.Func.fli_dyn_params)
}

// -------------------------------------------------------------------

// EnvState

// required .ok_msg.SVMapData vars = 1;
inline bool EnvState::has_vars() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EnvState::set_has_vars() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EnvState::clear_has_vars() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EnvState::clear_vars() {
  if (vars_ != NULL) vars_->::ok_msg::SVMapData::Clear();
  clear_has_vars();
}
inline const ::ok_msg::SVMapData& EnvState::vars() const {
  // @@protoc_insertion_point(field_get:ok_msg.EnvState.vars)
  return vars_ != NULL ? *vars_ : *default_instance_->vars_;
}
inline ::ok_msg::SVMapData* EnvState::mutable_vars() {
  set_has_vars();
  if (vars_ == NULL) vars_ = new ::ok_msg::SVMapData;
  // @@protoc_insertion_point(field_mutable:ok_msg.EnvState.vars)
  return vars_;
}
inline ::ok_msg::SVMapData* EnvState::release_vars() {
  clear_has_vars();
  ::ok_msg::SVMapData* temp = vars_;
  vars_ = NULL;
  return temp;
}
inline void EnvState::set_allocated_vars(::ok_msg::SVMapData* vars) {
  delete vars_;
  vars_ = vars;
  if (vars) {
    set_has_vars();
  } else {
    clear_has_vars();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.EnvState.vars)
}

// -------------------------------------------------------------------

// CompositionInit

// repeated .ok_msg.Func func = 1;
inline int CompositionInit::func_size() const {
  return func_.size();
}
inline void CompositionInit::clear_func() {
  func_.Clear();
}
inline const ::ok_msg::Func& CompositionInit::func(int index) const {
  // @@protoc_insertion_point(field_get:ok_msg.CompositionInit.func)
  return func_.Get(index);
}
inline ::ok_msg::Func* CompositionInit::mutable_func(int index) {
  // @@protoc_insertion_point(field_mutable:ok_msg.CompositionInit.func)
  return func_.Mutable(index);
}
inline ::ok_msg::Func* CompositionInit::add_func() {
  // @@protoc_insertion_point(field_add:ok_msg.CompositionInit.func)
  return func_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ok_msg::Func >&
CompositionInit::func() const {
  // @@protoc_insertion_point(field_list:ok_msg.CompositionInit.func)
  return func_;
}
inline ::google::protobuf::RepeatedPtrField< ::ok_msg::Func >*
CompositionInit::mutable_func() {
  // @@protoc_insertion_point(field_mutable_list:ok_msg.CompositionInit.func)
  return &func_;
}

// -------------------------------------------------------------------

// WhileInit

// optional .ok_msg.Func condition = 1;
inline bool WhileInit::has_condition() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WhileInit::set_has_condition() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WhileInit::clear_has_condition() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WhileInit::clear_condition() {
  if (condition_ != NULL) condition_->::ok_msg::Func::Clear();
  clear_has_condition();
}
inline const ::ok_msg::Func& WhileInit::condition() const {
  // @@protoc_insertion_point(field_get:ok_msg.WhileInit.condition)
  return condition_ != NULL ? *condition_ : *default_instance_->condition_;
}
inline ::ok_msg::Func* WhileInit::mutable_condition() {
  set_has_condition();
  if (condition_ == NULL) condition_ = new ::ok_msg::Func;
  // @@protoc_insertion_point(field_mutable:ok_msg.WhileInit.condition)
  return condition_;
}
inline ::ok_msg::Func* WhileInit::release_condition() {
  clear_has_condition();
  ::ok_msg::Func* temp = condition_;
  condition_ = NULL;
  return temp;
}
inline void WhileInit::set_allocated_condition(::ok_msg::Func* condition) {
  delete condition_;
  condition_ = condition;
  if (condition) {
    set_has_condition();
  } else {
    clear_has_condition();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.WhileInit.condition)
}

// optional .ok_msg.Func body = 2;
inline bool WhileInit::has_body() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WhileInit::set_has_body() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WhileInit::clear_has_body() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WhileInit::clear_body() {
  if (body_ != NULL) body_->::ok_msg::Func::Clear();
  clear_has_body();
}
inline const ::ok_msg::Func& WhileInit::body() const {
  // @@protoc_insertion_point(field_get:ok_msg.WhileInit.body)
  return body_ != NULL ? *body_ : *default_instance_->body_;
}
inline ::ok_msg::Func* WhileInit::mutable_body() {
  set_has_body();
  if (body_ == NULL) body_ = new ::ok_msg::Func;
  // @@protoc_insertion_point(field_mutable:ok_msg.WhileInit.body)
  return body_;
}
inline ::ok_msg::Func* WhileInit::release_body() {
  clear_has_body();
  ::ok_msg::Func* temp = body_;
  body_ = NULL;
  return temp;
}
inline void WhileInit::set_allocated_body(::ok_msg::Func* body) {
  delete body_;
  body_ = body;
  if (body) {
    set_has_body();
  } else {
    clear_has_body();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.WhileInit.body)
}

// -------------------------------------------------------------------

// StreamInit

// optional .ok_msg.Func src = 1;
inline bool StreamInit::has_src() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StreamInit::set_has_src() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StreamInit::clear_has_src() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StreamInit::clear_src() {
  if (src_ != NULL) src_->::ok_msg::Func::Clear();
  clear_has_src();
}
inline const ::ok_msg::Func& StreamInit::src() const {
  // @@protoc_insertion_point(field_get:ok_msg.StreamInit.src)
  return src_ != NULL ? *src_ : *default_instance_->src_;
}
inline ::ok_msg::Func* StreamInit::mutable_src() {
  set_has_src();
  if (src_ == NULL) src_ = new ::ok_msg::Func;
  // @@protoc_insertion_point(field_mutable:ok_msg.StreamInit.src)
  return src_;
}
inline ::ok_msg::Func* StreamInit::release_src() {
  clear_has_src();
  ::ok_msg::Func* temp = src_;
  src_ = NULL;
  return temp;
}
inline void StreamInit::set_allocated_src(::ok_msg::Func* src) {
  delete src_;
  src_ = src;
  if (src) {
    set_has_src();
  } else {
    clear_has_src();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.StreamInit.src)
}

// optional .ok_msg.Func snk = 2;
inline bool StreamInit::has_snk() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StreamInit::set_has_snk() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StreamInit::clear_has_snk() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StreamInit::clear_snk() {
  if (snk_ != NULL) snk_->::ok_msg::Func::Clear();
  clear_has_snk();
}
inline const ::ok_msg::Func& StreamInit::snk() const {
  // @@protoc_insertion_point(field_get:ok_msg.StreamInit.snk)
  return snk_ != NULL ? *snk_ : *default_instance_->snk_;
}
inline ::ok_msg::Func* StreamInit::mutable_snk() {
  set_has_snk();
  if (snk_ == NULL) snk_ = new ::ok_msg::Func;
  // @@protoc_insertion_point(field_mutable:ok_msg.StreamInit.snk)
  return snk_;
}
inline ::ok_msg::Func* StreamInit::release_snk() {
  clear_has_snk();
  ::ok_msg::Func* temp = snk_;
  snk_ = NULL;
  return temp;
}
inline void StreamInit::set_allocated_snk(::ok_msg::Func* snk) {
  delete snk_;
  snk_ = snk;
  if (snk) {
    set_has_snk();
  } else {
    clear_has_snk();
  }
  // @@protoc_insertion_point(field_set_allocated:ok_msg.StreamInit.snk)
}

// -------------------------------------------------------------------

// TopKSinkInit

// required uint64 k = 1;
inline bool TopKSinkInit::has_k() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TopKSinkInit::set_has_k() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TopKSinkInit::clear_has_k() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TopKSinkInit::clear_k() {
  k_ = GOOGLE_ULONGLONG(0);
  clear_has_k();
}
inline ::google::protobuf::uint64 TopKSinkInit::k() const {
  // @@protoc_insertion_point(field_get:ok_msg.TopKSinkInit.k)
  return k_;
}
inline void TopKSinkInit::set_k(::google::protobuf::uint64 value) {
  set_has_k();
  k_ = value;
  // @@protoc_insertion_point(field_set:ok_msg.TopKSinkInit.k)
}

// -------------------------------------------------------------------

// RangeInit

// optional int64 start = 1;
inline bool RangeInit::has_start() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RangeInit::set_has_start() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RangeInit::clear_has_start() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RangeInit::clear_start() {
  start_ = GOOGLE_LONGLONG(0);
  clear_has_start();
}
inline ::google::protobuf::int64 RangeInit::start() const {
  // @@protoc_insertion_point(field_get:ok_msg.RangeInit.start)
  return start_;
}
inline void RangeInit::set_start(::google::protobuf::int64 value) {
  set_has_start();
  start_ = value;
  // @@protoc_insertion_point(field_set:ok_msg.RangeInit.start)
}

// optional int64 step = 2;
inline bool RangeInit::has_step() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RangeInit::set_has_step() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RangeInit::clear_has_step() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RangeInit::clear_step() {
  step_ = GOOGLE_LONGLONG(0);
  clear_has_step();
}
inline ::google::protobuf::int64 RangeInit::step() const {
  // @@protoc_insertion_point(field_get:ok_msg.RangeInit.step)
  return step_;
}
inline void RangeInit::set_step(::google::protobuf::int64 value) {
  set_has_step();
  step_ = value;
  // @@protoc_insertion_point(field_set:ok_msg.RangeInit.step)
}

// required int64 limit = 3;
inline bool RangeInit::has_limit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RangeInit::set_has_limit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RangeInit::clear_has_limit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RangeInit::clear_limit() {
  limit_ = GOOGLE_LONGLONG(0);
  clear_has_limit();
}
inline ::google::protobuf::int64 RangeInit::limit() const {
  // @@protoc_insertion_point(field_get:ok_msg.RangeInit.limit)
  return limit_;
}
inline void RangeInit::set_limit(::google::protobuf::int64 value) {
  set_has_limit();
  limit_ = value;
  // @@protoc_insertion_point(field_set:ok_msg.RangeInit.limit)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ok_msg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ok_5fmsg_2fFLiSpec_2eproto__INCLUDED
